package org.haidy.servify.app.resources

import org.haidy.servify.R


data class DrawableResources(
    val logo: Int = R.drawable.logo,
    val eyeIcon: Int = R.drawable.eye_icon,
    val disabledEyeIcon: Int = R.drawable.disabled_eye_icon,
    val facebookIcon: Int = R.drawable.facebook_icon,
    val googleIcon: Int = R.drawable.google_icon,
    val resendIcon: Int = R.drawable.resend_icon,
    val helloImage: Int = R.drawable.hello_image,
    val arrangementImage: Int = R.drawable.arrangement_image,
    val solvingImage: Int = R.drawable.solving_image,
    val verifiedImage: Int = R.drawable.verified_image,
    val userImage: Int = R.drawable.user_image,
    val plusIcon: Int = R.drawable.plus_icon,
    val backIcon: Int = R.drawable.back_icon,
    val editProfile: Int = R.drawable.edit_profile_icon,
    val notification: Int = R.drawable.notification_icon,
    val language: Int = R.drawable.language_icon,
    val updatePassword: Int = R.drawable.update_password_icon,
    val themeIcon: Int = R.drawable.theme_icon,
    val helpAndSupportIcon: Int = R.drawable.help_and_suppor_icon,
    val contactUsIcon: Int = R.drawable.contact_us_icon,
    val privacyPolicyIcon: Int = R.drawable.privacy_policy_icon,
    val logoutIcon: Int = R.drawable.logout_icon,
    val egyptImage: Int = R.drawable.egypt_image,
    val homeNotificationIcon: Int = R.drawable.home_notification_icon,
    val menuIcon: Int = R.drawable.menu_icon,
    val searchIcon: Int = R.drawable.search_icon,
    val homeIcon: Int = R.drawable.home_icon,
    val bookingIcon: Int = R.drawable.booking_icon,
    val profileIcon: Int = R.drawable.profile_icon,
    val locationIcon: Int = R.drawable.location_icon,
    val supportIcon: Int = R.drawable.support_icon,
    val closeIcon: Int = R.drawable.close_icon,
    val notificationWithDotDrawerIcon: Int = R.drawable.notification_with_dot_drawer_icon,
    val profileDrawerIcon: Int = R.drawable.profile_drawer_icon,
    val settingsDrawerIcon: Int = R.drawable.settings_drawer_icon,
    val topScreenShape: Int = R.drawable.top_screen_shape,
    val editIcon: Int = R.drawable.edit_icon,
    val favIcon: Int = R.drawable.fav_icon,
    val startIcon: Int = R.drawable.star_icon,
    val filledStartIcon: Int = R.drawable.filled_start_icon,
    val directionIcon: Int = R.drawable.direction_icon,
    val walkIcon: Int = R.drawable.walk_icon,
    val arrowDropUpIcon: Int= R.drawable.arrow_drop_up_icon,
    val arrowDropDownIcon: Int = R.drawable.arrow_drop_down_icon,
    val visaLogo: Int = R.drawable.visa_logo,
    val meezaLogo: Int = R.drawable.meeza_logo,
    val masterCardLogo: Int = R.drawable.master_card_logo,
    val americanExpressLogo: Int = R.drawable.amex_logo,
    val addCardIcon: Int = R.drawable.add_card_icon,
    val specialistIcon: Int = R.drawable.specialist_icon,
    val phoneIcon: Int = R.drawable.phone_icon,
    val messageIcon: Int = R.drawable.message_icon,
    val cardIcon: Int = R.drawable.card_icon,
    val cashIcon: Int = R.drawable.cash_icon,
    val paymentReceiptCard: Int = R.drawable.payment_receipt_card,
    val successOrangeShape: Int = R.drawable.success_orange,
    val successGreenShape: Int = R.drawable.success_green,
    val filterIcon: Int = R.drawable.filter_icon,
    val notFoundImage: Int = R.drawable.not_found_image,
    val chatIcon: Int = R.drawable.chat_icon,
    val emojiIcon: Int = R.drawable.emoji_icon,
    val sendIcon: Int = R.drawable.send_icon
)

val DrawableDarkResources = DrawableResources(
    logo = R.drawable.logo,
)