package org.haidy.servify.app.navigation

object ServifyDestination {
    const val LOGIN = "Login"
    const val SIGNUP = "Signup"
    const val ON_BOARDING = "OnBoarding"
    const val HOME = "Home"
    const val SEND_OTP = "SendOtp"
    const val RESET_PASSWORD = "ResetPassword"
    const val VERIFY_CODE = "VerifyCode"
    const val VERIFY_EMAIL  = "VerifyEmail"
    const val PROFILE = "Profile"
    const val ADD_PHOTO = "AddPhoto"
    const val SETTINGS = "Settings"
    const val LANGUAGE = "Language"
    const val UPDATE_PASSWORD = "UpdatePassword"
    const val LOCATION = "Location"
    const val BOOKING_TRACK = "BookingTrack"
    const val SUPPORT = "Support"
    const val VERIFIED = "Verified"
    const val SERVICES = "Services"
    const val SPECIALISTS = "Specialists"
    const val FEEDBACK = "Feedback"
    const val BOOKING_CANCELLATION: String = "BookingCancellation"
    const val BOOKING_APPOINTMENT: String = "BookingAppointment"
    const val ADD_CARD: String = "AddCard"
    const val ADD_PAYMENT_METHOD: String = "AddPaymentMethod"
    const val PAYMENT_OPTION: String = "PaymentOption"
    const val PAYMENT_SUCCESS: String = "PaymentSuccess"
}