object BuildModules {
    const val ADMINISTRATION_APP = ":administration:app"
    const val ADMINISTRATION_FEATURE_ADMIN = ":administration:feature:admin"
    const val ADMINISTRATION_FEATURE_SUPPORT = ":administration:feature:support"
    const val ADMINISTRATION_DOMAIN_ADMIN = ":administration:domain:admin"
    const val ADMINISTRATION_DOMAIN_SUPPORT = ":administration:domain:support"
    const val ADMINISTRATION_REPOSITORY_ADMIN = ":administration:repository:admin"
    const val ADMINISTRATION_REPOSITORY_SUPPORT = ":administration:repository:support"
    const val ADMINISTRATION_CORE = ":administration:core"
    const val ADMINISTRATION_SHARED_UI = ":administration:shared_ui"
    const val END_USER_APP = ":administration:app"
    const val END_USER_FEATURE_CUSTOMER = ":end_user:feature:customer"
    const val END_USER_FEATURE_SPECIALIST = ":end_user:feature:specialist"
    const val END_USER_FEATURE_REGISTRATION = ":end_user:feature:registration"
    const val END_USER_DOMAIN_CUSTOMER = ":end_user:domain:customer"
    const val END_USER_DOMAIN_SPECIALIST = ":end_user:domain:specialist"
    const val END_USER_DOMAIN_REGISTRATION = ":end_user:domain:registration"
    const val END_USER_REPOSITORY_CUSTOMER = ":end_user:repository:customer"
    const val END_USER_REPOSITORY_SPECIALIST = ":end_user:repository:specialist"
    const val END_USER_REPOSITORY_REGISTRATION = ":end_user:repository:registration"
    const val END_USER_CORE = ":end_user:core"
    const val END_USER_SHARED_UI = ":end_user:shared_ui"
    const val DESIGN_SYSTEM = ":design_system"
}