package org.haidy.servify.app.resources.strings

interface IStringResources {
    val emailOrUsername: String
    val email: String
    val username: String
    val password: String
    val welcomeBack: String
    val doYouHaveAccount: String
    val forgotPassword: String
    val signup: String
    val signUp: String
    val login: String
    val doNotHaveAccount: String
    val registerNewAccount: String
    val phoneNumber: String
    val registerAs: String
    val register: String
    val user: String
    val specialist: String
    val skip: String
    val facebook: String
    val google: String
    val forgetPassword: String
    val enterYourEmailBelow: String
    val enterFourDigitCode: String
    val resendCode: String
    val send: String
    val confirm: String
    val theVerifyCodeWillExpireIn: String
    val resetPassword: String
    val enterTheNewPassword: String
    val newPassword: String
    val confirmNewPassword: String
    val emailIsRequired: String
    val invalidEmail: String
    val passwordIsRequired: String
    val invalidPassword: String
    val phoneNumberIsRequired: String
    val invalidPhoneNumber: String
    val invalidCredentials: String
    val requestFailed: String
    val enterTheVerifyCode: String
    val weSentVerificationCodeTo: String
    val verified: String
    val yourAccountIsVerified: String
    val explore: String
    val hello: String
    val arrangement: String
    val solving: String
    val helloPageDescription: String
    val arrangementPageDescription: String
    val solvingPageDescription: String
    val getStarted: String
    val addPhoto: String
    val addYourPhoto: String
    val addPhotoDescription: String
    val continueSteps: String
    val settings: String
    val editProfile: String
    val notifications: String
    val language: String
    val theme: String
    val helpAndSupport: String
    val contactUs: String
    val privacyPolicy: String
    val logout: String
    val updatePassword: String
    val on: String
    val off: String
    val english: String
    val arabic: String
    val egyptian: String
    val lightMode: String
    val darkMode: String
    val systemMode: String
    val address: String
    val gender: String
    val country: String
    val suggested: String
    val chooseTheme: String
    val cancel: String
    val oldPassword: String
    val passwordDoesNotMatch: String
    val showMore: String
    val offers: String
    val services: String
    val bestSpecialists: String
    val search: String
    val helloUser: String
    val howCanWeHelpYou: String
    val usernameShouldBeAtLeastFiveLength: String
    val pleaseSelectAnImage: String
    val profile: String
    val confirmPassword: String
    val governorate: String
    val signIn: String
    val alreadyHaveAccount: String
    val male: String
    val female: String
    val countryIsRequired: String
    val governorateIsRequired: String
    val imageUpdatedSuccessfully: String
    val nearestSpecialists: String
}